# Generated by Django 5.0.3 on 2024-04-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='Ползователь')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('subject', models.TextField(verbose_name='Сообщение')),
            ],
        ),
    ]
